# Generated by Django 5.1 on 2024-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
    ]
