# Generated by Django 5.1 on 2024-08-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_blog_header',
            field=models.BooleanField(default=False),
        ),
    ]
