# Generated by Django 5.1 on 2024-08-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_blog_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_blog_header',
            new_name='is_blog_featured',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_header',
            new_name='is_featured',
        ),
    ]
