# Generated by Django 5.1 on 2024-08-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_is_blog_header_post_is_blog_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='to_process',
            field=models.BooleanField(default=True),
        ),
    ]
