# Generated by Django 5.1 on 2024-08-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_to_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='to_process',
            field=models.BooleanField(default=True),
        ),
    ]
